### ISSUE TITLE
Project 1: requirements.txt is missing

### ISSUE THREAD

**Issue by theova** [spring-epfl/CS-523-public#1]
Hi,

In the README of project 1 it is stated that:
> You can install the dependant python libraries by running the command
> ```
> python3 -m pip install -r requirements.txt
>```
> in the directory of the skeleton.

However the file `requirements.txt` is missing.

Could you add the file or adapt the README accordingly?

Thanks a lot!

**Comment by bogdan-kulynych** [comment]
Hi, this is fixed already.
